# Generated by Django 5.2.4 on 2025-07-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
